<?php

/**
 * @file
 * Functions to support theming in the d8mdl theme.
 */

function d8_materialize_preprocess(&$variables, $hook) {
    if($hook == 'menu_local_task') {
        $url = $variables['link']['#url']->getInternalPath();
        $variables['url'] = $url;
    }
    if($hook == 'menu__main' || $hook == 'menu_local_tasks') {
        $is_front = Drupal::service('path.matcher')->isFrontPage();
        $variables['is_front'] = $is_front;
    }
}