definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  standard__front_page:
    weight: -50
    menu_name: main
    parent: ''
    expanded: false
    enabled: false
  user__page:
    enabled: true
    menu_name: account
    parent: ''
    weight: -47
    expanded: false
  user__logout:
    enabled: true
    menu_name: account
    parent: ''
    weight: -48
    expanded: false
langcode: es
