keys:
  public: 12c50348b2b8339e6476ad87cc33d563
  private: 6f5d3fe8f3185fe8374303d29d3e10bc
fallback: 1
languages_expected:
  languageCode: es
test_mode:
  enabled: false
  api_endpoint: dev.mollom.com
  keys:
    public: ''
    private: ''
  invalid:
    api_endpoint: fake-host
privacy_link: true
log_level: 4
connection_timeout_seconds: 3
api_endpoint: rest.mollom.com
captcha:
  audio:
    enabled: true
_core:
  default_config_hash: 8uHhdqIc3ARJWLcZ_gKimtOymT0SRxGryuDcC6S5Vx4
langcode: es
