display_denied_message: true
access_denied_message: 'Inicia sesión o crea una cuenta para ver esta página.'
access_denied_message_type: warning
redirect_authenticated_users_to: ''
user_login_route: user.register
default_redirect_code: '302'
match_noredirect_pages: ''
_core:
  default_config_hash: S3Ko6a4TBmaxzNlsc9sv9fvGk37cCwVCx84_WQj4J1M
langcode: es
