smtp_on: true
smtp_host: mail.gandi.net
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_username: info@drupalcampgdl.com
smtp_password: 'D8bAX:?X9%qd'
smtp_from: info@drupalcampgdl.com
smtp_fromname: 'Drupal Camp Guadalajara'
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
_core:
  default_config_hash: U7C23Wy4M4Eq8X8ExjU4n3yq7PtfU1S-jebw2hikU5g
langcode: es
